const constants = {
  ADD_STUDENT : "ADD_STUDENT",
  REMOVE_STUDENT : "REMOVE_STUDENT",
  UPDATE_STUDENT_NAME : "UPDATE_STUDENT_NAME",
  RATE_CLASS : "RATE_CLASS",
  UPLOADING_PROFILE : "UPLOADING_PROFILE",
  UPLOADING_PROGRESS : "UPLOADING_PROGRESS",
  UPLOADING_ST_NUM : "UPLOADING_ST_NUM",
  UPDATE_STUDENT_PROFILE : "UPDATE_STUDENT_PROFILE",
  HOVER_ON_ADD : "HOVER_ON_ADD",
  HOVER_GO_BACK : "HOVER_GO_BACK",
  ADD_STUDENT_CLICKED : "ADD_STUDENT_CLICKED",
  HOVER_ON_REMOVE : "HOVER_ON_REMOVE",
  REMOVE_STUDENT_CLICKED : "REMOVE_STUDENT_CLICKED",
  ADD_CHECKED : "ADD_CHECKED",
  REMOVE_CHECKED : "REMOVE_CHECKED",
  INITIALIZE_CHECKED: "INITIALIZE_CHECKED",
  FILTER_TIME : "FILTER_TIME"
}

export default constants ;
