const constants = {
  ADD_STUDENT : "ADD_STUDENT",
  REMOVE_STUDENT : "REMOVE_STUDENT",
  UPDATE_STUDENT_NAME : "UPDATE_STUDENT_NAME",
  RATE_CLASS : "RATE_CLASS",
  UPLOADING_PROFILE : "UPLOADING_PROFILE",
  UPLOADING_PROGRESS : "UPLOADING_PROGRESS",
  UPLOADING_ST_NUM : "UPLOADING_ST_NUM",
  UPDATE_STUDENT_PROFILE : "UPDATE_STUDENT_PROFILE"
}

export default constants ;
